### ISSUE TITLE
Ability to delete a stack in all relevant accounts/ou's

### ISSUE THREAD

**Issue by tstroband** [OlafConijn/AwsOrganizationFormation#13]
It would be nice to have the ability to delete a particular stack in all or specified accounts/ou's/regions. This could be a special org-formation command that takes the organization.yml and parameters to identify the accounts/ou's/regions

**Comment by OlafConijn** [comment]
added 2 commands:
1) describe-stacks [--stack-name stackname] which will list all stacks deployed under this name by org-formation 
2) delete-stacks <stack-name> which will delete all stacks deployed under this name by org-formation.

commit: https://github.com/OlafConijn/AwsOrganizationFormation/commit/371fc05074b06856b728a07358d7db811f0d5bd5
