### ISSUE TITLE
Template format error: The Value field of every Outputs member must evaluate to a String and not a Map.

### ISSUE THREAD

**Issue by tstroband** [OlafConijn/AwsOrganizationFormation#15]
When referencing a list instead of a value in a stack that spans multiple accounts the following error is produced:

```ERROR: Template format error: The Value field of every Outputs member must evaluate to a String and not a Map. ```

Steps to reproduce: 

1. Create a hosted zone for "somedomain.com"  in account A.
2. Create a single template that defines the following resources:
 
- A hosted zone for "sub.somedomain.com" in account B
- An NS resource record for domain B in the "somedomain.com" zone in account A using the "!GetAtt SubHostedZone.NameServers" value.

Example of template for step 2: 

```
  # hosted zone in account B
  HostedZone:
    Type: AWS::Route53::HostedZone
    OrganizationBindings:
      Regions: eu-west-1
      Accounts: !Ref AccountB
    Properties:
      HostedZoneConfig:
        Comment: Domain Hosted Zone
      Name: !Sub '${AWSAccount.Tags.subdomain}.${rootHostedZoneName}.'
      HostedZoneTags:
        - Key: Application
          Value: cso
        - Key: Component
          Value: domains
        - Key: Aspect
          Value: addressing

  # Parent NS record in root zone in account A
  ParentNsRecord:
    Type: AWS::Route53::RecordSet
    OrganizationBindings:
      Regions: eu-west-1
      Accounts: !Ref AccountA
    Properties:
      Type: NS
      HostedZoneName: !Ref rootHostedZoneName
      Name: !Sub '${AWSAccount.Tags.subdomain}.${rootHostedZoneName}.'
      TTL: 86400
      ResourceRecords: !GetAtt HostedZone.NameServers
```

The "HostedZone.NameServers" returns a List<String>. As CloudFormation outputs are used to handle cross-account references the error most likely is caused by that.

Note that there's probably an easier way to reproduce this but this is what I've got...

**Comment by OlafConijn** [comment]
fixed specifically for NameServers.
