### ISSUE TITLE
Support MFA!!

### ISSUE THREAD

**Issue by tstroband** [OlafConijn/AwsOrganizationFormation#8]

**Comment by tstroband** [comment]
Typically the AWS configuration consists of 2 files:

- `.aws/credentials`
- `. aws/config`

The credentials file holds the credentials in the form of an access key and a secret key.
The capabilities of the config and credentials file are explained in detail here: [https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)

A typical configuration is as follows:

`.aws/credentials`:
```
[default]
aws_access_key_id = AKIAI...
aws_secret_access_key = Gvh1qY...

[myorg-master]
aws_access_key_id = AKIAI...
aws_secret_access_key = hYddea...
```

`.aws/config`:
```
[profile myorg-child-admin]
role_arn = arn:aws:iam::<account-id>:role/MyAdminRole
source_profile = myorg-master
mfa_serial = arn:aws:iam::<account-id>:mfa/<my-username>
region = eu-west-1
output = json
color = ff0000
```

**Comment by OlafConijn** [comment]
added mfa support. see commit 25b5d0456c890dab19da1eca8cee1266f55b29b6
