### ISSUE TITLE
CloudTrail isLogging is set to false in example template

### ISSUE THREAD

**Issue by craighurley** [OlafConijn/AwsOrganizationFormation#85]
In the most recent CloudTrail example template, `isLogging` is set to `false`: https://github.com/OlafConijn/AwsOrganizationFormation/blob/9763379272dcc8043e7e8c88ab096a24d3f71ea3/examples/templates/cloudtrail.yml#L98

Is that intentional?

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html#cfn-cloudtrail-trail-islogging

**Comment by OlafConijn** [comment]
indeed was not. changed it, thanks!
